version: '3'


services:
  web: &web
    build:
      context: .
    image: pis-web:latest
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_ANALYTICS_TRACKING_ID=#######
    command: python main.py