name: CI/CD - Upgrade Chart and Deploy 
on:
  workflow_dispatch:
    release:
      types: [published]

permissions:
  contents: read    

jobs:
  deploy:
    name: deploy to totoro
    runs-on: ubuntu-latest
    steps:

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-totoro

      - name: Check out code
        uses: actions/checkout@v2

      - name: Seteo variables
        id: set-vars
        run: |
          export APP_VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
          export CHART_VERSION=$(echo $GITHUB_EVENT_RELEASE_NAME | cut -d ' ' -f 2)
      
      - name: Actualizar chart
        run: |
          helm upgrade --install pis ./.chart/ --set-string appVersion=$APP_VERSION --version $CHART_VERSION