# version 1.0
name: Build and push to docker hub
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: anopa/pis